version: '3'
services:
  app:
    image: node:16-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm start"
    restart: always
